create table if not exists public.bookings (
 id bigint generated by default as identity primary key, created_at timestamptz default now(),
 name text not null, phone text not null, email text, event text not null, date date not null,
 start text not null, "end" text, venue text not null, guests text, music text, message text,
 status text not null default 'new'
);

create table if not exists public.requests (
 id bigint generated by default as identity primary key, created_at timestamptz default now(),
 name text not null, song text not null, message text, approved boolean default false,
 status text not null default 'pending'
);

create table if not exists public.live_settings (
 id int primary key default 1 check (id = 1),
 is_live boolean not null default false,
 event_name text not null default 'DJ Joesika Live',
 auto_approve boolean not null default false,
 updated_at timestamptz default now()
);
insert into public.live_settings (id) values (1) on conflict (id) do nothing;

alter table public.bookings add column if not exists status text not null default 'new';
alter table public.requests add column if not exists status text not null default 'pending';

alter table public.bookings enable row level security;
alter table public.requests enable row level security;
alter table public.live_settings enable row level security;

drop policy if exists "public can submit bookings" on public.bookings;
drop policy if exists "dj can read bookings" on public.bookings;
drop policy if exists "dj can update bookings" on public.bookings;
drop policy if exists "public can submit requests" on public.requests;
drop policy if exists "public can read approved requests" on public.requests;
drop policy if exists "dj can read requests" on public.requests;
drop policy if exists "dj can update requests" on public.requests;
drop policy if exists "dj can delete requests" on public.requests;
drop policy if exists "public can read live settings" on public.live_settings;
drop policy if exists "dj can update live settings" on public.live_settings;

create policy "public can submit bookings" on public.bookings for insert to anon, authenticated with check (true);
create policy "dj can read bookings" on public.bookings for select to authenticated using (true);
create policy "dj can update bookings" on public.bookings for update to authenticated using (true) with check (true);

create policy "public can submit requests" on public.requests for insert to anon, authenticated with check (true);
create policy "public can read approved requests" on public.requests for select to anon using (approved = true);
create policy "dj can read requests" on public.requests for select to authenticated using (true);
create policy "dj can update requests" on public.requests for update to authenticated using (true) with check (true);
create policy "dj can delete requests" on public.requests for delete to authenticated using (true);

create policy "public can read live settings" on public.live_settings for select to anon, authenticated using (true);
create policy "dj can update live settings" on public.live_settings for update to authenticated using (true) with check (true);

do $$ begin
  alter publication supabase_realtime add table public.requests;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.live_settings;
exception when duplicate_object then null; end $$;
