import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, CheckCircle2, Headphones, Menu, MessageCircle, Music2, Phone, Send, Sparkles, X, Zap, LogOut, ShieldCheck, Radio, Trash2, Play, Check, XCircle } from 'lucide-react'
import { hasSupabase, supabase } from './lib/supabase'

const PHONE_DISPLAY = '07459 742667'
const WHATSAPP = '447459742667'
const TIKTOKS = ['https://www.tiktok.com/player/v1/7557639099822525718','https://www.tiktok.com/player/v1/7557639007356521750']
const services = [
  ['Weddings','A polished soundtrack from arrival to the last dance.'],['Birthdays','Big energy, favourite tracks and unforgettable celebrations.'],['Private Parties','A tailored mix for your guests, venue and vibe.'],['Corporate Events','Professional music programming for launches and company events.'],['Clubs & Bars','Dancefloor-focused sets across Afrobeats, Amapiano, R&B and more.'],['Ghanaian & African Events','Highlife, Hiplife, Afrobeats and classics for every generation.']
]
function wa(text){ return `https://wa.me/${WHATSAPP}?text=${encodeURIComponent(text)}` }
function Nav(){const [open,setOpen]=useState(false); return <header className="nav"><a className="brand" href="#home"><span className="brand-icon">🎧</span><span>DJ <b>JOESIKA</b></span></a><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'open':''}>{['home','about','services','videos','live','book'].map(x=><a key={x} onClick={()=>setOpen(false)} href={`#${x}`}>{x==='book'?'Book Now':x[0].toUpperCase()+x.slice(1)}</a>)}</nav></header>}
function Hero(){return <section id="home" className="hero"><div className="hero-shade"/><div className="hero-content"><div className="eyebrow"><Sparkles size={16}/> Professional DJ • London & beyond</div><h1>YOUR EVENT.<br/><span>YOUR MUSIC.</span><br/>YOUR VIBE.</h1><p>Premium DJ entertainment for weddings, birthdays, private parties, clubs, corporate events and African celebrations.</p><div className="actions"><a className="btn gold" href="#book"><CalendarDays/> Book DJ Joesika</a><a className="btn glass" href={wa('Hi DJ Joesika, I would like to enquire about booking you for an event.')} target="_blank"><MessageCircle/> WhatsApp</a></div><div className="hero-contact"><Phone size={18}/>{PHONE_DISPLAY}</div></div></section>}
function About(){return <section id="about" className="section split"><div><div className="kicker">MEET THE DJ</div><h2>Music that brings <span>people together.</span></h2><p className="lead">DJ Joesika delivers energetic, audience-focused sets designed around the people in the room. From Ghanaian classics and Afrobeats to Amapiano, R&B, Hip-Hop and party favourites, every event gets its own soundtrack.</p><div className="chips"><span>Afrobeats</span><span>Highlife</span><span>Amapiano</span><span>R&B</span><span>Hip-Hop</span><span>Party Classics</span></div></div><div className="about-card"><Headphones size={48}/><h3>Professional Event Experience</h3><p>Personalised music planning, guest requests, announcements and a direct booking experience from enquiry to event day.</p><a href="#book">Check availability →</a></div></section>}
function Services(){return <section id="services" className="section dark"><div className="center"><div className="kicker">SERVICES</div><h2>Ready for every <span>celebration.</span></h2></div><div className="cards">{services.map(([t,d],i)=><article className="service" key={t}><div className="number">0{i+1}</div><Music2/><h3>{t}</h3><p>{d}</p></article>)}</div></section>}
function Videos(){return <section id="videos" className="section"><div className="center"><div className="kicker">WATCH DJ JOESIKA</div><h2>See the <span>energy.</span></h2><p className="lead narrow">Highlights from TikTok. Follow Joesikal for more performances and updates.</p></div><div className="video-grid">{TIKTOKS.map((src,i)=><div className="phone-frame" key={src}><iframe title={`DJ Joesika TikTok ${i+1}`} src={src} allow="fullscreen; autoplay; encrypted-media" allowFullScreen /></div>)}</div></section>}
function Booking(){const initial={name:'',phone:'',email:'',event:'Wedding',date:'',start:'',end:'',venue:'',guests:'',music:'',message:''}; const [f,setF]=useState(initial); const [status,setStatus]=useState(''); const change=e=>setF({...f,[e.target.name]:e.target.value}); async function submit(e){e.preventDefault(); const msg=`*DJ BOOKINGS*\n\nName: ${f.name}\nPhone: ${f.phone}\nEmail: ${f.email||'Not provided'}\nEvent: ${f.event}\nDate: ${f.date}\nTime: ${f.start}${f.end?' - '+f.end:''}\nVenue: ${f.venue}\nGuests: ${f.guests||'Not specified'}\nMusic: ${f.music||'Not specified'}\nMore details: ${f.message||'None'}`; if(hasSupabase){await supabase.from('bookings').insert({...f});} setStatus('Opening WhatsApp with your booking details…'); window.open(wa(msg),'_blank','noopener,noreferrer');}
return <section id="book" className="section booking"><div className="booking-copy"><div className="kicker">BOOK DJ JOESIKA</div><h2>Let’s make your event <span>unforgettable.</span></h2><p>Complete the form and your booking details will be prepared as a WhatsApp message to DJ Joesika.</p><div className="booking-points"><p><CheckCircle2/> Fast WhatsApp enquiry</p><p><CheckCircle2/> Music tailored to your event</p><p><CheckCircle2/> Mobile-friendly booking</p></div><a className="phone-link" href={`tel:+${WHATSAPP}`}><Phone/> {PHONE_DISPLAY}</a></div><form className="form" onSubmit={submit}><div className="row"><label>Your name<input required name="name" value={f.name} onChange={change}/></label><label>Phone number<input required name="phone" value={f.phone} onChange={change}/></label></div><div className="row"><label>Email<input type="email" name="email" value={f.email} onChange={change}/></label><label>Event type<select name="event" value={f.event} onChange={change}><option>Wedding</option><option>Birthday</option><option>Private Party</option><option>Corporate Event</option><option>Club / Bar</option><option>Ghanaian / African Event</option><option>Other</option></select></label></div><div className="row"><label>Date<input required type="date" name="date" value={f.date} onChange={change}/></label><label>Venue / Location<input required name="venue" value={f.venue} onChange={change}/></label></div><div className="row three"><label>Start<input required type="time" name="start" value={f.start} onChange={change}/></label><label>End<input type="time" name="end" value={f.end} onChange={change}/></label><label>Guests<input type="number" name="guests" value={f.guests} onChange={change}/></label></div><label>Music preferences<input name="music" placeholder="Afrobeats, Highlife, Amapiano, R&B, Francophone, etc…" value={f.music} onChange={change}/></label><label>Anything else?<textarea name="message" rows="4" value={f.message} onChange={change}/></label><button className="btn gold full"><MessageCircle/> Send Booking to WhatsApp</button>{status&&<small>{status}</small>}</form></section>}
function Live(){const [name,setName]=useState(''); const [song,setSong]=useState(''); const [note,setNote]=useState(''); const [sent,setSent]=useState(''); const [feed,setFeed]=useState([]); const [settings,setSettings]=useState({is_live:false,event_name:'DJ Joesika Live',auto_approve:false});
useEffect(()=>{if(!hasSupabase)return; let mounted=true; const load=async()=>{const [{data:r},{data:l}]=await Promise.all([supabase.from('requests').select('*').eq('approved',true).order('created_at',{ascending:false}).limit(8),supabase.from('live_settings').select('*').eq('id',1).single()]); if(mounted){setFeed(r||[]);if(l)setSettings(l)}};load(); const channel=supabase.channel('public-live').on('postgres_changes',{event:'*',schema:'public',table:'requests'},()=>load()).on('postgres_changes',{event:'UPDATE',schema:'public',table:'live_settings'},p=>setSettings(p.new)).subscribe(); return()=>{mounted=false;supabase.removeChannel(channel)}},[]);
async function send(e){e.preventDefault(); if(!name||!song)return; if(!settings.is_live){setSent('DJ Joesika is not live right now. Please use the booking or WhatsApp options.');return} if(hasSupabase){const approved=!!settings.auto_approve; const {error}=await supabase.from('requests').insert({name,song,message:note,approved,status:approved?'approved':'pending'}); setSent(error?'Could not send request. Please use WhatsApp.':approved?'Request sent and added to the live wall!':'Request sent to DJ Joesika!');}else{window.open(wa(`*LIVE SONG REQUEST*\nName: ${name}\nSong: ${song}\nMessage: ${note||'None'}`),'_blank'); setSent('Opening WhatsApp…')} setSong('');setNote('')}
return <section id="live" className="section live"><div className="live-head"><div><div className={`live-pill ${settings.is_live?'':'offline'}`}><span/> {settings.is_live?'LIVE NOW':'CURRENTLY OFFLINE'}</div><h2>{settings.is_live?settings.event_name:'Request a song or '} <span>{settings.is_live?'':'shout-out.'}</span></h2><p>{settings.is_live?'Send your request straight to DJ Joesika from your phone.':'Live requests open when DJ Joesika starts an event.'}</p></div><Zap size={72}/></div><div className="live-grid"><form className="request" onSubmit={send}><label>Your name / table<input value={name} onChange={e=>setName(e.target.value)} required disabled={!settings.is_live}/></label><label>Song / artist<input value={song} onChange={e=>setSong(e.target.value)} required disabled={!settings.is_live}/></label><label>Shout-out or dedication<textarea value={note} onChange={e=>setNote(e.target.value)} rows="3" disabled={!settings.is_live}/></label><button className="btn gold full" disabled={!settings.is_live}><Send/> {settings.is_live?'Send Request':'Requests Closed'}</button>{sent&&<small>{sent}</small>}</form><div className="feed"><h3><MessageCircle/> Live request wall</h3>{feed.length?feed.map(x=><div className="feed-item" key={x.id}><b>{x.song}</b><span>requested by {x.name}</span>{x.message&&<small>{x.message}</small>}</div>):<div className="empty"><Music2/><p>Approved requests will appear here during a live programme.</p></div>}</div></div></section>}

function DjControlRoom(){const [session,setSession]=useState(null);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [requests,setRequests]=useState([]);const [bookings,setBookings]=useState([]);const [settings,setSettings]=useState({id:1,is_live:false,event_name:'DJ Joesika Live',auto_approve:false});
useEffect(()=>{if(!hasSupabase)return; supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>subscription.unsubscribe()},[]);
useEffect(()=>{if(!session)return; let active=true; const load=async()=>{const [{data:r},{data:b},{data:l}]=await Promise.all([supabase.from('requests').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('bookings').select('*').order('created_at',{ascending:false}).limit(50),supabase.from('live_settings').select('*').eq('id',1).single()]);if(active){setRequests(r||[]);setBookings(b||[]);if(l)setSettings(l)}};load(); const ch=supabase.channel('dj-control-room').on('postgres_changes',{event:'*',schema:'public',table:'requests'},load).on('postgres_changes',{event:'*',schema:'public',table:'live_settings'},load).subscribe();return()=>{active=false;supabase.removeChannel(ch)}},[session]);
async function login(e){e.preventDefault();setError('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message)}
async function patchRequest(id,changes){await supabase.from('requests').update(changes).eq('id',id);setRequests(v=>v.map(x=>x.id===id?{...x,...changes}:x))}
async function removeRequest(id){await supabase.from('requests').delete().eq('id',id);setRequests(v=>v.filter(x=>x.id!==id))}
async function patchSettings(changes){const next={...settings,...changes,updated_at:new Date().toISOString()};const {data}=await supabase.from('live_settings').update(changes).eq('id',1).select().single();if(data)setSettings(data);else setSettings(next)}
async function patchBooking(id,status){await supabase.from('bookings').update({status}).eq('id',id);setBookings(v=>v.map(x=>x.id===id?{...x,status}:x))}
if(!hasSupabase)return <main className="admin-shell"><div className="admin-login"><h1>Supabase required</h1></div></main>;
if(!session)return <main className="admin-shell"><form className="admin-login" onSubmit={login}><div className="kicker">PRIVATE ACCESS</div><h1>DJ JOESIKA<br/><span>CONTROL ROOM</span></h1><p>Sign in with the DJ account created in Supabase Authentication.</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="btn gold full"><ShieldCheck/> Sign In</button>{error&&<small>{error}</small>}<a href="/">← Back to website</a></form></main>;
const pending=requests.filter(x=>x.status==='pending'||(!x.approved&&x.status!=='declined'));return <main className="admin-shell"><header className="admin-top"><div><b>🎧 DJ JOESIKA</b><span>CONTROL ROOM</span></div><button className="btn glass" onClick={()=>supabase.auth.signOut()}><LogOut/> Sign out</button></header><section className="admin-content"><div className="admin-title"><div><div className="kicker">PRIVATE DJ DASHBOARD</div><h1>Live Control Room</h1></div><div className={`status-big ${settings.is_live?'on':''}`}><Radio/> {settings.is_live?'LIVE':'OFFLINE'}</div></div><div className="control-panel"><label>Event name<input value={settings.event_name} onChange={e=>setSettings({...settings,event_name:e.target.value})} onBlur={()=>patchSettings({event_name:settings.event_name})}/></label><button className={`btn ${settings.is_live?'danger':'gold'}`} onClick={()=>patchSettings({is_live:!settings.is_live})}>{settings.is_live?'■ END EVENT':'● GO LIVE'}</button><label className="switch-line"><input type="checkbox" checked={settings.auto_approve} onChange={e=>patchSettings({auto_approve:e.target.checked})}/> Auto-approve requests to public wall</label></div><div className="admin-grid"><section className="admin-card"><h2><span>{pending.length}</span> New Requests</h2>{requests.length?requests.map(r=><article className={`request-card ${r.status}`} key={r.id}><div className="request-main"><small>{new Date(r.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} • {r.name}</small><strong>🎵 {r.song}</strong>{r.message&&<p>📣 {r.message}</p>}</div><div className="request-actions"><button title="Approve" onClick={()=>patchRequest(r.id,{approved:true,status:'approved'})}><Check/></button><button title="Playing" onClick={()=>patchRequest(r.id,{approved:true,status:'playing'})}><Play/></button><button title="Done" onClick={()=>patchRequest(r.id,{approved:false,status:'done'})}><CheckCircle2/></button><button title="Decline" onClick={()=>patchRequest(r.id,{approved:false,status:'declined'})}><XCircle/></button><button title="Delete" onClick={()=>removeRequest(r.id)}><Trash2/></button></div></article>):<div className="empty"><Music2/><p>No requests yet.</p></div>}</section><section className="admin-card"><h2>Bookings</h2>{bookings.length?bookings.map(b=><article className="booking-card" key={b.id}><small>{b.date} • {b.event}</small><strong>{b.name}</strong><span>{b.venue} • {b.phone}</span><select value={b.status||'new'} onChange={e=>patchBooking(b.id,e.target.value)}><option value="new">New</option><option value="confirmed">Confirmed</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></article>):<div className="empty"><CalendarDays/><p>No bookings yet.</p></div>}</section></div></section></main>}

function Footer(){return <footer><div className="footer-brand"><span>🎧</span><div>DJ <b>JOESIKA</b><small>Your Event. Your Music. Your Vibe.</small></div></div><div><h4>Contact</h4><a href={`tel:+${WHATSAPP}`}>{PHONE_DISPLAY}</a><a href={wa('Hi DJ Joesika')} target="_blank">WhatsApp DJ Joesika or </a></div><div><h4>Social</h4><span>TikTok: Joesikal</span><span>Facebook: Dada Joesika</span><span>Instagram: Dada Joesika</span><span>Snapchat: Joesikaj</span></div><p className="copyright">© {new Date().getFullYear()} DJ Joesika. All rights reserved.</p></footer>}
export default function App(){if(window.location.pathname==='/dj')return <DjControlRoom/>;return <><Nav/><Hero/><About/><Services/><Videos/><Live/><Booking/><Footer/><a className="float-wa" href={wa('Hi DJ Joesika, I would like to enquire about an event.')} target="_blank" aria-label="Chat on WhatsApp"><MessageCircle/></a></>}
